/**
 * The `DO NOT EDIT` banner shared by every always-overwritten generated file.
 *
 * It carries **no timestamp/version/filename** — anything time- or input-dependent
 * would break byte-identical idempotency and snapshot stability (CLAUDE.md rules
 * 3 & 5). It lives in its own dependency-free module so the pure emitters can use
 * it without pulling in the side-effecting writer.
 */
export const GENERATED_BANNER = `/**
 * DO NOT EDIT — generated by openapi-nextjs.
 * Regenerate with \`npx openapi-nextjs generate\`. Changes here will be overwritten.
 */`;
