import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { describe, expect, it } from "vitest";

import { loadSpec } from "../../src/spec/load.js";
import { buildRoutePlans } from "../../src/plan/routePlan.js";
import { buildComponentSchemas } from "../../src/emit/zod.js";
import { emitGenerated } from "../../src/emit/generated.js";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "..", "fixtures");

async function emitEdgeCases(
  schemasModule = "../../../_schemas.generated",
): Promise<string> {
  const { bundled, dereferenced } = await loadSpec(join(fixturesDir, "edge-cases.yaml"));
  const components = buildComponentSchemas(bundled);
  const [plan] = buildRoutePlans(bundled);
  const [mockPlan] = buildRoutePlans(dereferenced);
  if (plan === undefined || mockPlan === undefined) throw new Error("expected plans");
  return emitGenerated(plan, {
    resolveRef: components.resolveRef,
    schemasModule,
    mockPlan,
  });
}

describe("emitGenerated — edge-cases route", () => {
  it("carries the DO NOT EDIT banner with no timestamp", async () => {
    const source = await emitEdgeCases();
    expect(source).toContain("DO NOT EDIT — generated by openapi-nextjs.");
    // No ISO date / year-like token would mean a timestamp slipped in.
    expect(source).not.toMatch(/\b20\d{2}-\d{2}-\d{2}\b/);
  });

  it("imports zod and the shared schemas namespace at the right depth", async () => {
    const source = await emitEdgeCases();
    expect(source).toContain(`import { z } from "zod";`);
    expect(source).toContain(`import * as schemas from "../../../_schemas.generated";`);
  });

  it("emits coerce-mode param schemas", async () => {
    const source = await emitEdgeCases();
    expect(source).toContain(
      "export const GetUserPostsParams = z.object({ userId: z.coerce.string() });",
    );
    expect(source).toContain(
      "export const GetUserPostsQuery = z.object({ limit: z.coerce.number().int().optional() });",
    );
  });

  it("references shared component schemas via the namespace", async () => {
    const source = await emitEdgeCases();
    expect(source).toContain(
      "export const PostUsersUserIdPostsBody = z.lazy(() => schemas.PostSchema);",
    );
    expect(source).toContain(
      "export type GetUserPostsResponse = z.infer<typeof schemas.PostListSchema>;",
    );
  });

  it("synthesizes a mock factory with cycle-broken, format-aware values", async () => {
    const source = await emitEdgeCases();
    expect(source).toContain(
      "export function mockGetUserPostsResponse(): GetUserPostsResponse {",
    );
    // format: uuid → the deterministic uuid placeholder.
    expect(source).toContain('"id":"00000000-0000-0000-0000-000000000000"');
    // Post → Author → Post cycle: the inner Post is truncated to a required-only
    // shell ({ id, title }) so the mock still typechecks against the generated type.
    expect(source).toContain(
      '"author":{"name":"string","posts":[{"id":"00000000-0000-0000-0000-000000000000","title":"string"}]}',
    );
  });

  it("emits no mock factory for the empty 204 DELETE response", async () => {
    const source = await emitEdgeCases();
    expect(source).not.toContain("mockDeleteUserPostsResponse");
    expect(source).toContain("export const DeleteUserPostsParams");
  });

  it("is deterministic across repeated calls", async () => {
    const a = await emitEdgeCases();
    const b = await emitEdgeCases();
    expect(a).toBe(b);
  });

  it("is a stable snapshot", async () => {
    expect(await emitEdgeCases()).toMatchSnapshot();
  });
});
